#cloud-config
users:
  - name: ${ssh_username}
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_key}
    shell: /bin/bash
  - name: root
    lock_passwd: true
package_update: true
package_upgrade: true
chpasswd:
  expire: false
packages:
  - vim
  - htop
  - fail2ban
  - unattended-upgrades
  - nfs-common
  - net-tools
  - open-iscsi
  - lvm2
  - iptables
  - git
  - telnet
  - vim
  - software-properties-common
  - resolvconf
  - jq
  - curl
runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers ${ssh_username}' /etc/ssh/sshd_config
  - apt-get update
  - apt-get install -y linux-headers-$(uname -r)
  - echo "RateLimitIntervalSec=0" >> /etc/systemd/journald.conf
  - echo "RateLimitBurst=0" >> /etc/systemd/journald.conf
  - systemctl restart systemd-journald.service
  - echo 'net.ipv4.ip_nonlocal_bind=1' > /etc/sysctl.d/enable-non-local-bind.conf
  - if ! grep /run/shm /etc/fstab ; then echo 'none     /run/shm     tmpfs     defaults,noexec,nosuid,nodev     0     0' >> /etc/fstab ; fi
  - mv /etc/ssh-host-keys/* /etc/ssh/ || true
  - cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local || true
  - systemctl restart systemd-sysctl
write_files:
  - path: "/etc/sysctl.d/enable-ip4-forward.conf"
    content: "net.ipv4.ip_forward=1"
    owner: "root:root"
    permissions: "0644"
  - path: "/etc/sysctl.d/enable-ip6-forward.conf"
    content: "net.ipv6.conf.all.forwarding=1"
    owner: "root:root"
    permissions: "0644"
power_state:
  delay: "+1"
  mode: reboot
  message: reboot
  timeout: 300
  condition: true
